# Generated by Django 6.0.7 on 2026-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "пользователь", "verbose_name_plural": "пользователи"},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=50, unique=True, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Имя пользователя"),
        ),
    ]
