# Generated by Django 6.0.7 on 2026-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(max_length=100, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "мотоцикл",
                "verbose_name_plural": "мотоциклы",
            },
        ),
    ]
