# Generated by Django 6.0.7 on 2026-08-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_moto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("milage", models.PositiveIntegerField(verbose_name="Пробег")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год регистрации")),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milage",
                        to="vehicle.car",
                        verbose_name="Машина",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milage",
                        to="vehicle.moto",
                        verbose_name="Мотоцикл",
                    ),
                ),
            ],
            options={
                "verbose_name": "пробег",
                "verbose_name_plural": "пробег",
                "ordering": ("-year",),
            },
        ),
    ]
