# Generated by Django 6.0.7 on 2026-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_car_owner_moto_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
    ]
