# Generated by Django 6.0.7 on 2026-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0005_car_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Цена машины"),
        ),
        migrations.AddField(
            model_name="moto",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Цена мотоцикла"),
        ),
    ]
